### ISSUE TITLE
[FEATURE]: 能否对简短描述超过50个字符时作出提示

### ISSUE THREAD

**Issue by xyeluo** [chunshand/gitcommit#5]
插件很好用，感谢作者的开发!

能否增加对简短描述超过50个字符时作出提示，用git commit -m添加简短描述对字符长度有限制，下面是相关文档的说明

https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

**Comment by chunshand** [comment]
感谢你对插件的评价，晚点更新后发布。

**Comment by xyeluo** [comment]
我的描述有点问题，我的意思是除了’具体内容(非必填)‘以外的字符串加起来不能超过50个字符

**Comment by chunshand** [comment]
get

**Comment by xyeluo** [comment]
才看到……，我已经提了一个pr可以考虑一下🙌
