### ISSUE TITLE
[FEATURE]: 仅使用emoji+subject格式作为提交信息

### ISSUE THREAD

**Issue by xyeluo** [chunshand/gitcommit#7]
能否提供一个选择，仅使用'emoji subject'格式作为提交信息，就像下面这种效果
![image](https://github.com/chunshand/gitcommit/assets/76687240/0a188b55-6036-4af1-8074-05dae473b6fb)

**Comment by xyeluo** [comment]
按照这种格式的话我觉得可以参考插件市场`gitemoji`插件的列表形式做一个类似功能，如果作者比较忙的话，我可以尝试做这个功能

**Comment by xyeluo** [comment]
那要写的代码应该挺多的，我先提代码格式化的pr吧，统一一下代码风格

**Comment by chunshand** [comment]
好 加油
